name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    services:
      fastapi-app:
        image: your-dockerhub-username/fastapi-devsecops_web:latest  # 👈 replace this with your image
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Wait for FastAPI to start
        run: |
          echo "Waiting for FastAPI to become healthy..."
          for i in {1..10}; do
            if curl -s http://localhost:8000/health > /dev/null; then
              echo "✅ FastAPI is up!"
              break
            fi
            echo "⏳ Waiting... ($i/10)"
            sleep 5
          done

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "http://fastapi-app:8000"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
        continue-on-error: true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html
