name: DevSecOps CI/CD (SAST + DAST + Deploy Staging)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sast:
    name: SAST (Bandit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit scan
        run: |
          mkdir -p reports
          bandit -r app -f html -o reports/bandit-report.html || true

      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: reports/bandit-report.html

  build_and_dast:
    name: Build, Run & DAST (ZAP)
    needs: sast
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fastapi-app:${{ github.sha }} .

      - name: Run container
        run: docker run -d --name fastapi-app -p 8000:8000 fastapi-app:${{ github.sha }}

      - name: Wait for app to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8000/ >/dev/null; then
              echo "OK"
              break
            fi
            sleep 2
          done

      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: "http://host.docker.internal:8000"
          cmd_options: "-r zap-report.html"
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
